{% set name = "pytest-workflow" %}
{% set version = "1.2.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13cbc74ff66bb1c6901518c3303d5171461fb83d119b305130ce90bbc17bb1d8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - jsonschema
    - pip
    - pytest >=4
    - python >=3.5
    - pyyaml
    - setuptools
  run:
    - jsonschema
    - pytest >=4
    - python >=3.5
    - pyyaml

test:
  imports:
    - pytest_workflow

about:
  home: https://github.com/LUMC/pytest-workflow
  license: GNU Affero General Public v3 or later (AGPLv3+)
  license_family: AGPL
  license_file: LICENSE
  summary: A pytest plugin for configuring workflow/pipeline tests using YAML files
  doc_url: https://pytest-workflow.readthedocs.io

extra:
  recipe-maintainers:
    - rhpvorderman
    - sndrtj
    - DavyCats
