{% set name = "pytest-workflow" %}
{% set version = "1.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b83a3e7a36976d35fa33c76dec3c38545c91c8276bc24d9ec44b95418a07ab58

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - jsonschema
    - pip
    - pytest >=5.4.0
    - python >=3.6
    - pyyaml
    - setuptools
  run:
    - jsonschema
    - pytest >=5.4.0
    - python >=3.6
    - pyyaml

test:
  imports:
    - pytest_workflow

about:
  home: https://github.com/LUMC/pytest-workflow
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  summary: A pytest plugin for configuring workflow/pipeline tests using YAML files
  doc_url: https://pytest-workflow.readthedocs.io

extra:
  recipe-maintainers:
    - rhpvorderman
    - DavyCats
    - Redmar-van-den-Berg
