travis:
  secure:
    BINSTAR_TOKEN: p27MICs3pD2hKp1Ke4nEEUEgC4dtzv8JoLbx0NqU0/RWtCXGSagGGNLNhTATeO4U5jPD/WZx/fEOBfpVmdJaP5mPGtD8G5peAKw+YCdEsTeRMbCLW255I9GZcU4sAJFKDiFxcrxYz22OvTX9i81p0Ff7GYAwKr9lLYPaRVMGDLkqdXfpP9c1eU4EAUibH6UFAa2ricqWEid12KArpMNkKAAt9GMf3QXnh5qb0lOtAKtAF7rTWYCoQdFLa9fiTCveSQWoZCYqcwIZXnWBHuQgG7AbK9j+YWXvsG0ZuRv/qRIYHzqErICNqnKq4A6emhVh1+3oV7Br1BivwWKd0Ab64gbAQHBgIM2ZrtQltMEfL3XWMTslGrWiqFZ/w1q9J2WjhQxWa0hWekiyC6/uUYRSMFzLyTtUR/hm0YM8V3QTodNYvKTHX4LJBGMQji9/qLWDtuikI4TZlrpEIwvJ2e5JPc4QirojWaLTAgX0I8uDp63b3y42E5O3YMTwkBgMZBqXb4/e34hM4eFnVwAjEMouc4CcyrB3uAfyz4rskRtL1QcVFg2/ZW2/RJbRBu/rQrfXRRpNU3+XQfgNlRBe5PvHPTdvLXK9ojfJNiid24IOydL3pwe/mTR0vdRRPpQcq9BtfdkQU+Wu1tajmHFR6qvzrJfxFZBTcdlLT7jH/XqQCFo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
